name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read
  packages: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # optional but recommended if you use branch protection or custom domains
    environment: github-pages      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build          # adjust if your build script is different

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3      # ← new major

        with:
          path: ./dist             # change if your build output lives elsewhere

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4               # ← new major
